locally tested version number check!

diff --git a/.github/workflows/check-version.yml b/.github/workflows/check-version.yml
--- a/.github/workflows/check-version.yml
+++ b/.github/workflows/check-version.yml
@@ -12,44 +12,51 @@ jobs:
 
       - name: Compare versions
         run: |
-          source_version=`cat CMakeLists.txt | grep -o "PARLAY VERSION [0-9].[0-9].[0-9]" | grep -o "[0-9].[0-9].[0-9]"`
+          source_version=`cat CMakeLists.txt | grep -Eo "PARLAY VERSION [0-9]+\.[0-9]+\.[0-9]+" | grep -Eo "[0-9]+\.[0-9]+\.[0-9]+"`
           echo "Source version is $source_version"
           source_major_version=`echo $source_version | awk '{split($0,a,"."); print a[1]}'`
           source_minor_version=`echo $source_version | awk '{split($0,a,"."); print a[2]}'`
           source_patch_version=`echo $source_version | awk '{split($0,a,"."); print a[3]}'`
-          echo "  Major: $source_major_version, Minor: $source_minor_version, Patch: $source_patch_version"
+          echo "- Major: $source_major_version, Minor: $source_minor_version, Patch: $source_patch_version"
           
           master_version=`git show refs/remotes/origin/master:CMakeLists.txt | grep -o "PARLAY VERSION [0-9].[0-9].[0-9]" | grep -o "[0-9].[0-9].[0-9]"`
           echo "Master version is $master_version"
-          master_major_version=`echo $source_version | awk '{split($0,a,"."); print a[1]}'`
-          master_minor_version=`echo $source_version | awk '{split($0,a,"."); print a[2]}'`
-          master_patch_version=`echo $source_version | awk '{split($0,a,"."); print a[3]}'`
-          echo "  Major: $master_major_version, Minor: $master_minor_version, Patch: $master_patch_version"
-
+          master_major_version=`echo $master_version | awk '{split($0,a,"."); print a[1]}'`
+          master_minor_version=`echo $master_version | awk '{split($0,a,"."); print a[2]}'`
+          master_patch_version=`echo $master_version | awk '{split($0,a,"."); print a[3]}'`
+          echo "- Major: $master_major_version, Minor: $master_minor_version, Patch: $master_patch_version"
+          
           function version { echo "$@" | awk -F. '{ printf("%04d%04d%04d\n", $1,$2,$3); }'; }
-
+          
           if [ $(version $source_version) -le $(version $master_version) ]; then
-            echo "Version number on the source branch ($source_version) must be greater than the master branch ($master_version)"
-            exit 1
+            echo "Version number on the source branch ($source_version) must be greater than the master branch ($master_version). Fail" && exit 1
           fi
-
-          let $master_major_version++
-          let $master_minor_version++
-          let $master_patch_version++
+          
+          let "master_major_version_pp = master_major_version + 1"
+          let "master_minor_version_pp = master_minor_version + 1"
+          let "master_patch_version_pp = master_patch_version + 1"
           
           if [ $source_major_version -gt $master_major_version ]; then
-            echo "Major version number on the source branch ($source_version) increased by more than one compared to the master branch ($master_version)"
-            exit 1
+            echo "Major version was incremented"
+            if [ $source_major_version -gt $master_major_version_pp ]; then
+              echo "- Major version number was incremented by more than one. Fail" && exit 1
+            elif [ $source_minor_version -ne 0 ]; then
+              echo "- Minor version should now be 0. Fail" && exit 1
+            elif [ $source_patch_version -gt 1 ]; then
+              echo "- Patch version should now be 0 or 1. Fail" && exit 1
+            fi
+            elif [ $source_minor_version -gt $master_minor_version ]; then
+              echo "Minor version was incremented"
+            if [ $source_minor_version -gt $master_minor_version_pp ]; then
+              echo "- Minor version number was incremented by more than one. Fail" && exit 1
+            elif [ $source_patch_version -gt 1 ]; then
+              echo "- Patch version should now be 0 or 1. Fail" && exit 1
+            fi
+            else
+              echo "Patch version was incremented"
+            if [ $source_patch_version -gt $master_patch_version_pp ]; then
+              echo "- Patch version number was incremented by more than one. Fail" && exit 1
+            fi
           fi
           
-          if [ $source_minor_version -gt $master_minor_version ]; then
-            echo "Minor version number on the source branch ($source_version) increased by more than one compared to the master branch ($master_version)"
-            exit 1
-          fi
-          
-          if [ $source_patch_version -gt $master_patch_version ]; then
-            echo "Patch version number on the source branch ($source_version) increased by more than one compared to the master branch ($master_version)"
-            exit 1
-          fi
-
-          echo "New version number looks good. Success"
+          echo "-  New version number looks good. Success"
